/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.gui_menu;

import java.awt.BorderLayout;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.business.Cola;
import model.business.ListaCircular;
import model.business.ListaDoble;
import model.business.ListaSimple;
import model.business.Logic;
import model.business.Pila;
import model.gui_menu.opcionesCola.Opciones_Eliminar_LCola;
import model.gui_menu.opcionesCola.Opciones_Ingresar_LCola;
import model.gui_menu.opcionesCola.Opciones_Modificar_LCola;
import model.gui_menu.opcionesCola.Opciones_Mostrar_LCola;
import model.gui_menu.opcionesCola.Opciones_Total_LCola;
import model.gui_menu.opcionesPila.Opciones_Eliminar_LPILA;
import model.gui_menu.opcionesPila.Opciones_Ingresar_LPILA;
import model.gui_menu.opcionesPila.Opciones_Modificar_LPILA;
import model.gui_menu.opcionesPila.Opciones_Mostrar_LPILA;
import model.gui_menu.opcionesPila.Opciones_Total_LPILA;
import model.gui_menu.opcionesListaCircular.Opciones_Eliminar_LCircular;
import model.gui_menu.opcionesListaCircular.Opciones_Ingresar_LCircular;
import model.gui_menu.opcionesListaCircular.Opciones_Modificar_LCircular;
import model.gui_menu.opcionesListaCircular.Opciones_Mostrar_LCircular;
import model.gui_menu.opcionesListaCircular.Opciones_Total_LCircular;
import model.gui_menu.opcionesListaDoble.Opciones_Eliminar_LDoble;
import model.gui_menu.opcionesListaDoble.Opciones_Ingresar_LDoble;
import model.gui_menu.opcionesListaDoble.Opciones_Modificar_LDoble;
import model.gui_menu.opcionesListaDoble.Opciones_Mostrar_LDoble;
import model.gui_menu.opcionesListaDoble.Opciones_Total_LDoble;
import model.gui_menu.opcionesListaSimple.Opciones_Eliminar;
import model.gui_menu.opcionesListaSimple.Opciones_Ingresar;
import model.gui_menu.opcionesListaSimple.Opciones_Modificar;
import model.gui_menu.opcionesListaSimple.Opciones_Mostrar;
import model.gui_menu.opcionesListaSimple.Opciones_Total;
import model.gui_menu.opciones_otros_metodos.Opciones_Metodo_Burbuja;

public final class Menu extends javax.swing.JFrame {

    protected ListaSimple l;
    protected ListaDoble lD;
    protected ListaCircular lC;
    protected Pila p;
    protected Cola c;
    //    protected ListaCirc lD;
    private final Logic logic;

    /**
     * Creates new form NewJFrame
     *
     * @param l
     * @param lD
     * @param lC
     * @param p
     * @param c
     */
    public Menu(ListaSimple l, ListaDoble lD, ListaCircular lC, Pila p, Cola c) {

        logic = new Logic();
        this.c = c;
        this.p = p;
        this.l = l;
        this.lD = lD;
        this.lC = lC;
        super.setUndecorated(true);
        initComponents();
        super.setLocationRelativeTo(null);
        derechos();
        this.setVisible(true);
        getjLabel4().setText("Estudiantes registrados :" + l.getTamano());

    }

    /**
     * Creates new form NewJFrame for listsimple
     *
     * @param l
     */
    public Menu(ListaSimple l) {
        logic = new Logic();
        this.l = l;
        super.setUndecorated(true);
        initComponents();
        super.setLocationRelativeTo(null);
        derechos();
        this.setVisible(true);
        getjLabel4().setText("Estudiantes registrados :" + l.getTamano());

    }

    /**
     * Creates new form NewJFrame for listDouble
     *
     * @param lD
     */
    public Menu(ListaDoble lD) {
        logic = new Logic();
        this.lD = lD;
        super.setUndecorated(true);
        initComponents();
        super.setLocationRelativeTo(null);
        derechos();
        this.setVisible(true);
        getjLabel4().setText("Estudiantes registrados :" + l.getTamano());

    }

    public Menu() {
        logic = new Logic();
        super.setUndecorated(true);
        initComponents();
        super.setLocationRelativeTo(null);
        derechos();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jlabelDerechos = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        titu1 = new javax.swing.JLabel();
        titu2 = new javax.swing.JLabel();
        fondoTitu = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        fondoDerechos = new javax.swing.JLabel();
        fondoOpciones = new javax.swing.JLabel();
        jlUser = new javax.swing.JLabel();
        fondoUser = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel_Menu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabelDerechos.setBackground(new java.awt.Color(255, 255, 255));
        jlabelDerechos.setFont(new java.awt.Font("Dialog", 1, 9)); // NOI18N
        jlabelDerechos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jlabelDerechos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 220, 30));

        jPanel5.setBackground(new java.awt.Color(0, 255, 0));
        jPanel5.setForeground(new java.awt.Color(153, 0, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titu1.setBackground(new java.awt.Color(0, 102, 102));
        titu1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        titu1.setText("Listas");
        jPanel5.add(titu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        titu2.setBackground(new java.awt.Color(255, 0, 0));
        titu2.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        titu2.setText("Enlazadas");
        jPanel5.add(titu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 120, -1));

        fondoTitu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/gui_menu/iconos/fondo.jpg"))); // NOI18N
        fondoTitu.setText("jLabel7");
        fondoTitu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(0, 0, 0)));
        jPanel5.add(fondoTitu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 60));

        salir.setBackground(new java.awt.Color(255, 255, 255));
        salir.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/gui_menu/iconos/salir.png"))); // NOI18N
        salir.setText(" Salir");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        jPanel2.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 80, 30));

        jComboBox1.setBackground(new java.awt.Color(1, 255, 135));
        jComboBox1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Lista Simples", "1. Ingresar ", "2. Mostrar", "3. Modificar", "4. Eliminar", "4. Total de Estudiantes", "6. Lista preterminada" }));
        jComboBox1.setBorder(new javax.swing.border.MatteBorder(null));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox1MousePressed(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 200, 40));

        jComboBox2.setBackground(new java.awt.Color(1, 255, 135));
        jComboBox2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Lista Dobles", "1. Ingresar ", "2. Mostrar", "3. Modificar", "4. Eliminar", "4. Total de Estudiantes", "6. Lista preterminada" }));
        jComboBox2.setBorder(new javax.swing.border.MatteBorder(null));
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox2MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox2MousePressed(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 200, 40));

        jComboBox3.setBackground(new java.awt.Color(1, 255, 135));
        jComboBox3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Lista Circular", "1. Ingresar ", "2. Mostrar", "3. Modificar", "4. Eliminar", "4. Total de Estudiantes", "6. Lista preterminada" }));
        jComboBox3.setBorder(new javax.swing.border.MatteBorder(null));
        jComboBox3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox3MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox3MousePressed(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 200, 40));

        jComboBox4.setBackground(new java.awt.Color(1, 255, 135));
        jComboBox4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Cola", "1. Ingresar ", "2. Mostrar", "3. Modificar", "4. Eliminar", "4. Total de Estudiantes", "6. Lista preterminada" }));
        jComboBox4.setBorder(new javax.swing.border.MatteBorder(null));
        jComboBox4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox4MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox4MousePressed(evt);
            }
        });
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 200, 40));

        jComboBox5.setBackground(new java.awt.Color(1, 255, 135));
        jComboBox5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBox5.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  Pila", "1. Ingresar ", "2. Mostrar", "3. Modificar", "4. Eliminar", "4. Total de Estudiantes", "6. Lista preterminada" }));
        jComboBox5.setBorder(new javax.swing.border.MatteBorder(null));
        jComboBox5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox5MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox5MousePressed(evt);
            }
        });
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 200, 40));

        jComboBox6.setBackground(new java.awt.Color(1, 255, 135));
        jComboBox6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBox6.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " Otros metodos", "Ordenamiento burbuja", "Ordenamiento Quicksort" }));
        jComboBox6.setBorder(new javax.swing.border.MatteBorder(null));
        jComboBox6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox6MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox6MousePressed(evt);
            }
        });
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 200, 40));

        fondoDerechos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/gui_menu/iconos/fondo.jpg"))); // NOI18N
        fondoDerechos.setText("jLabel11");
        jPanel2.add(fondoDerechos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 220, 50));

        fondoOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/gui_menu/iconos/fondo.jpg"))); // NOI18N
        fondoOpciones.setText("jLabel11");
        fondoOpciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(fondoOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 200, 50));

        jlUser.setBackground(new java.awt.Color(255, 255, 255));
        jlUser.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/gui_menu/iconos/usuario (1).png"))); // NOI18N
        jlUser.setText(" Tony");
        jPanel2.add(jlUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 120, -1));

        fondoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/model/gui_menu/iconos/fondo.jpg"))); // NOI18N
        fondoUser.setText("jLabel11");
        jPanel2.add(fondoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 220, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 600));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Estudiantes registrados");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 280, 36));

        jLabel5.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.foreground"));
        jLabel5.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Las listas están basadas en lista de Estudiantes  de la UCR y otros metodos");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 450, 36));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 780, 60));

        jPanel_Menu.setBackground(new java.awt.Color(204, 204, 204));
        jPanel_Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 102), 2));
        jPanel_Menu.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 780, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        // TODO add your handling code here:

        System.exit(1);
    }//GEN-LAST:event_salirMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:Opciones

    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1MouseEntered

    private void jComboBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MousePressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        opcionesMenuListaSimple(0);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jComboBox2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2MouseEntered

    private void jComboBox2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2MousePressed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        //Lista Doble
        opcionesMenuListaDoble(0);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3MouseClicked

    private void jComboBox3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3MouseEntered

    private void jComboBox3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3MousePressed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        ///LCircular
        opcionesMenuListaCircular(0);
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4MouseClicked

    private void jComboBox4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4MouseEntered

    private void jComboBox4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4MousePressed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        //Cola
        opcionesMenuListaCola(0);
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5MouseClicked

    private void jComboBox5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5MouseEntered

    private void jComboBox5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5MousePressed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
        //Pila
        opcionesMenuPila(0);
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6MouseClicked

    private void jComboBox6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6MouseEntered

    private void jComboBox6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6MousePressed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
        ///otros metodos
        opcionesMenuOtrosMetodos(0);

    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked
    public void opcionesMenuListaSimple(int n) {
        if (jComboBox1.getSelectedIndex() == 1 || n == 1) {
            System.out.println("Se seleccionó la opción 1");
            Opciones_Ingresar oI = new Opciones_Ingresar(this, l);
            jPanel_Menu.removeAll();
            oI.setSize(810, 540);
            oI.setLocation(0, 0);
            jPanel_Menu.add(oI, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox1.getSelectedIndex() == 2 || n == 2) {
            System.out.println("Se seleccionó la opción 2");
            Opciones_Mostrar oM = new Opciones_Mostrar(this, l);
            jPanel_Menu.removeAll();
            oM.setSize(810, 540);
            oM.setLocation(0, 0);
            jPanel_Menu.add(oM, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox1.getSelectedIndex() == 3 || n == 3) {
            System.out.println("Se seleccionó la opción 3");
            Opciones_Modificar oM = new Opciones_Modificar(this, l);
            jPanel_Menu.removeAll();
            oM.setSize(810, 540);
            oM.setLocation(0, 0);
            jPanel_Menu.add(oM, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox1.getSelectedIndex() == 4 || n == 4) {
            System.out.println("Se seleccionó la opción 4");
            Opciones_Eliminar oE = new Opciones_Eliminar(this, l);
            jPanel_Menu.removeAll();
            oE.setSize(810, 540);
            oE.setLocation(0, 0);
            jPanel_Menu.add(oE, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox1.getSelectedIndex() == 5 || n == 5) {
            System.out.println("Se seleccionó la opción 5");
            getjLabel4().setText("Estudiantes registrados :" + l.getTamano());
            Opciones_Total oE = new Opciones_Total(this, l);
            jPanel_Menu.removeAll();
            oE.setSize(810, 540);
            oE.setLocation(0, 0);
            jPanel_Menu.add(oE, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();

        }
        if (jComboBox1.getSelectedIndex() == 6 || n == 6) {
            int tamano = Integer.parseInt(JOptionPane.showInputDialog("Tamano de la Lista"));
            l = logic.addRamdonStudentLSimple(l, tamano);
        }
    }

    public void opcionesMenuListaDoble(int n) {
        if (jComboBox2.getSelectedIndex() == 1 || n == 1) {
            System.out.println("Se seleccionó la opción 1");
            Opciones_Ingresar_LDoble oI = new Opciones_Ingresar_LDoble(this, lD);
            jPanel_Menu.removeAll();
            oI.setSize(810, 540);
            oI.setLocation(0, 0);
            jPanel_Menu.add(oI, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox2.getSelectedIndex() == 2 || n == 2) {
            System.out.println("Se seleccionó la opción 2");
            Opciones_Mostrar_LDoble oM = new Opciones_Mostrar_LDoble(this, lD);
            jPanel_Menu.removeAll();
            oM.setSize(810, 540);
            oM.setLocation(0, 0);
            jPanel_Menu.add(oM, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox2.getSelectedIndex() == 3 || n == 3) {
            System.out.println("Se seleccionó la opción 3");
            Opciones_Modificar_LDoble oM = new Opciones_Modificar_LDoble(this, lD);
            jPanel_Menu.removeAll();
            oM.setSize(810, 540);
            oM.setLocation(0, 0);
            jPanel_Menu.add(oM, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox2.getSelectedIndex() == 4 || n == 4) {
            System.out.println("Se seleccionó la opción 4");
            Opciones_Eliminar_LDoble oE = new Opciones_Eliminar_LDoble(this, lD);
            jPanel_Menu.removeAll();
            oE.setSize(810, 540);
            oE.setLocation(0, 0);
            jPanel_Menu.add(oE, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox2.getSelectedIndex() == 5 || n == 5) {
            System.out.println("Se seleccionó la opción 5");
            getjLabel4().setText("Estudiantes registrados :" + lD.getTamano());
            Opciones_Total_LDoble oE = new Opciones_Total_LDoble(this, lD);
            jPanel_Menu.removeAll();
            oE.setSize(810, 540);
            oE.setLocation(0, 0);
            jPanel_Menu.add(oE, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();

        }
        if (jComboBox2.getSelectedIndex() == 6 || n == 6) {
            int tamano = Integer.parseInt(JOptionPane.showInputDialog("Tamano de la Lista"));
            lD = logic.addRamdonStudentLDouble(lD, tamano);
        }
    }

    public void opcionesMenuListaCircular(int n) {
        if (jComboBox3.getSelectedIndex() == 1 || n == 1) {
            System.out.println("Se seleccionó la opción 1");
            Opciones_Ingresar_LCircular oI = new Opciones_Ingresar_LCircular(this, lC);
            jPanel_Menu.removeAll();
            oI.setSize(810, 540);
            oI.setLocation(0, 0);
            jPanel_Menu.add(oI, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox3.getSelectedIndex() == 2 || n == 2) {
            System.out.println("Se seleccionó la opción 2");
            Opciones_Mostrar_LCircular oM = new Opciones_Mostrar_LCircular(this, lC);
            jPanel_Menu.removeAll();
            oM.setSize(810, 540);
            oM.setLocation(0, 0);
            jPanel_Menu.add(oM, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox3.getSelectedIndex() == 3 || n == 3) {
            System.out.println("Se seleccionó la opción 3");
            Opciones_Modificar_LCircular oM = new Opciones_Modificar_LCircular(this, lC);
            jPanel_Menu.removeAll();
            oM.setSize(810, 540);
            oM.setLocation(0, 0);
            jPanel_Menu.add(oM, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox3.getSelectedIndex() == 4 || n == 4) {
            System.out.println("Se seleccionó la opción 4");
            Opciones_Eliminar_LCircular oE = new Opciones_Eliminar_LCircular(this, lC);
            jPanel_Menu.removeAll();
            oE.setSize(810, 540);
            oE.setLocation(0, 0);
            jPanel_Menu.add(oE, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox3.getSelectedIndex() == 5 || n == 5) {
            System.out.println("Se seleccionó la opción 5");
            getjLabel4().setText("Estudiantes registrados :" + lC.getTamano());
            Opciones_Total_LCircular oE = new Opciones_Total_LCircular(this, lC);
            jPanel_Menu.removeAll();
            oE.setSize(810, 540);
            oE.setLocation(0, 0);
            jPanel_Menu.add(oE, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();

        }
        if (jComboBox3.getSelectedIndex() == 6 || n == 6) {
            int tamano = Integer.parseInt(JOptionPane.showInputDialog("Tamano de la Lista"));
            lC = logic.addRamdonStudentLCircular(lC, tamano);
        }
    }

    public void opcionesMenuListaCola(int n) {
        if (jComboBox4.getSelectedIndex() == 1 || n == 1) {
            System.out.println("Se seleccionó la opción 1");
            Opciones_Ingresar_LCola oI = new Opciones_Ingresar_LCola(this, c);
            jPanel_Menu.removeAll();
            oI.setSize(810, 540);
            oI.setLocation(0, 0);
            jPanel_Menu.add(oI, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox4.getSelectedIndex() == 2 || n == 2) {
            System.out.println("Se seleccionó la opción 2");
            Opciones_Mostrar_LCola oM = new Opciones_Mostrar_LCola(this, c);
            jPanel_Menu.removeAll();
            oM.setSize(810, 540);
            oM.setLocation(0, 0);
            jPanel_Menu.add(oM, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox4.getSelectedIndex() == 3 || n == 3) {
            System.out.println("Se seleccionó la opción 3");
            Opciones_Modificar_LCola oM = new Opciones_Modificar_LCola(this, c);
            jPanel_Menu.removeAll();
            oM.setSize(810, 540);
            oM.setLocation(0, 0);
            jPanel_Menu.add(oM, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox4.getSelectedIndex() == 4 || n == 4) {
            System.out.println("Se seleccionó la opción 4");
            Opciones_Eliminar_LCola oE = new Opciones_Eliminar_LCola(this, c);
            jPanel_Menu.removeAll();
            oE.setSize(810, 540);
            oE.setLocation(0, 0);
            jPanel_Menu.add(oE, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox4.getSelectedIndex() == 5 || n == 5) {
            System.out.println("Se seleccionó la opción 5");
            getjLabel4().setText("Estudiantes registrados :" + c.getTamano());
            Opciones_Total_LCola oE = new Opciones_Total_LCola(this, c);
            jPanel_Menu.removeAll();
            oE.setSize(810, 540);
            oE.setLocation(0, 0);
            jPanel_Menu.add(oE, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();

        }
        if (jComboBox4.getSelectedIndex() == 6 || n == 6) {
            int tamano = Integer.parseInt(JOptionPane.showInputDialog("Tamano de la Lista"));
            c = logic.addRamdonStudentCola(c, tamano);
        }
    }

    public void opcionesMenuPila(int n) {
        if (jComboBox5.getSelectedIndex() == 1 || n == 1) {
            System.out.println("Se seleccionó la opción 1");
            Opciones_Ingresar_LPILA oI = new Opciones_Ingresar_LPILA(this, p);
            jPanel_Menu.removeAll();
            oI.setSize(810, 540);
            oI.setLocation(0, 0);
            jPanel_Menu.add(oI, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox5.getSelectedIndex() == 2 || n == 2) {
            System.out.println("Se seleccionó la opción 2");
            Opciones_Mostrar_LPILA oM = new Opciones_Mostrar_LPILA(this, p);
            jPanel_Menu.removeAll();
            oM.setSize(810, 540);
            oM.setLocation(0, 0);
            jPanel_Menu.add(oM, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox5.getSelectedIndex() == 3 || n == 3) {
            System.out.println("Se seleccionó la opción 3");
            Opciones_Modificar_LPILA oM = new Opciones_Modificar_LPILA(this, p);
            jPanel_Menu.removeAll();
            oM.setSize(810, 540);
            oM.setLocation(0, 0);
            jPanel_Menu.add(oM, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox5.getSelectedIndex() == 4 || n == 4) {
            System.out.println("Se seleccionó la opción 4");
            Opciones_Eliminar_LPILA oE = new Opciones_Eliminar_LPILA(this, p);
            jPanel_Menu.removeAll();
            oE.setSize(810, 540);
            oE.setLocation(0, 0);
            jPanel_Menu.add(oE, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox5.getSelectedIndex() == 5 || n == 5) {
            System.out.println("Se seleccionó la opción 5");
            getjLabel4().setText("Estudiantes registrados :" + l.getTamano());
            Opciones_Total_LPILA oE = new Opciones_Total_LPILA(this, p);
            jPanel_Menu.removeAll();
            oE.setSize(810, 540);
            oE.setLocation(0, 0);
            jPanel_Menu.add(oE, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();

        }
        if (jComboBox5.getSelectedIndex() == 6 || n == 6) {
            int tamano = Integer.parseInt(JOptionPane.showInputDialog("Tamano de la Lista"));
            p = logic.addRamdonStudentPila(p, tamano);
        }
    }

    public void opcionesMenuOtrosMetodos(int n) {
        if (jComboBox6.getSelectedIndex() == 1 || n == 1) {
            System.out.println("Se seleccionó la opción 1");
            Opciones_Metodo_Burbuja oI = new Opciones_Metodo_Burbuja(this, l, lD, lC, p, c);
            jPanel_Menu.removeAll();
            oI.setSize(810, 540);
            oI.setLocation(0, 0);
            jPanel_Menu.add(oI, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        /*
        if (jComboBox1.getSelectedIndex() == 2 || n == 2) {
            System.out.println("Se seleccionó la opción 2");
            Opciones_Mostrar_LPILA oM = new Opciones_Mostrar_LPILA(this, l);
            jPanel_Menu.removeAll();
            oM.setSize(810, 540);
            oM.setLocation(0, 0);
            jPanel_Menu.add(oM, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox1.getSelectedIndex() == 3 || n == 3) {
            System.out.println("Se seleccionó la opción 3");
            Opciones_Modificar_LPILA oM = new Opciones_Modificar_LPILA(this, l);
            jPanel_Menu.removeAll();
            oM.setSize(810, 540);
            oM.setLocation(0, 0);
            jPanel_Menu.add(oM, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox1.getSelectedIndex() == 4 || n == 4) {
            System.out.println("Se seleccionó la opción 4");
            Opciones_Eliminar_LPILA oE = new Opciones_Eliminar_LPILA(this, p);
            jPanel_Menu.removeAll();
            oE.setSize(810, 540);
            oE.setLocation(0, 0);
            jPanel_Menu.add(oE, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();
        }
        if (jComboBox1.getSelectedIndex() == 5 || n == 5) {
            System.out.println("Se seleccionó la opción 5");
            getjLabel4().setText("Estudiantes registrados :" + l.getTamano());
            Opciones_Total_LPILA oE = new Opciones_Total_LPILA(this, l);
            jPanel_Menu.removeAll();
            oE.setSize(810, 540);
            oE.setLocation(0, 0);
            jPanel_Menu.add(oE, BorderLayout.CENTER);
            jPanel_Menu.revalidate();
            jPanel_Menu.repaint();

        }
        if (jComboBox6.getSelectedIndex() == 6 || n == 6) {
            int tamano = Integer.parseInt(JOptionPane.showInputDialog("Tamano de la Lista"));
            p = logic.addRamdonStudentPila(p, tamano);
        }
         */
    }

    private void derechos() {
// Obtener año actual
        int anioActual = java.time.Year.now().getValue();

        // Mensaje de derechos reservados
        String mensajePieDeAplicacion = "© " + anioActual + " Todos los derechos reservados.";
        jlabelDerechos.setText(mensajePieDeAplicacion);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondoDerechos;
    private javax.swing.JLabel fondoOpciones;
    private javax.swing.JLabel fondoTitu;
    private javax.swing.JLabel fondoUser;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel_Menu;
    private javax.swing.JLabel jlUser;
    private javax.swing.JLabel jlabelDerechos;
    private javax.swing.JLabel salir;
    private javax.swing.JLabel titu1;
    private javax.swing.JLabel titu2;
    // End of variables declaration//GEN-END:variables

    public JLabel getjLabel1() {
        return jlabelDerechos;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jlabelDerechos = jLabel1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JPanel getjPanel_Menu() {
        return jPanel_Menu;
    }

    public void setjPanel_Menu(JPanel jPanel4) {
        this.jPanel_Menu = jPanel4;
    }

    public JPanel getjPanel5() {
        return jPanel5;
    }

    public void setjPanel5(JPanel jPanel5) {
        this.jPanel5 = jPanel5;
    }

    public ListaSimple getL() {
        return l;
    }

    public void setL(ListaSimple l) {
        this.l = l;
    }

    public JLabel getFondoDerechos() {
        return fondoDerechos;
    }

    public void setFondoDerechos(JLabel fondoDerechos) {
        this.fondoDerechos = fondoDerechos;
    }

    public JLabel getFondoOpciones() {
        return fondoOpciones;
    }

    public void setFondoOpciones(JLabel fondoOpciones) {
        this.fondoOpciones = fondoOpciones;
    }

    public JLabel getFondoTitu() {
        return fondoTitu;
    }

    public void setFondoTitu(JLabel fondoTitu) {
        this.fondoTitu = fondoTitu;
    }

    public JLabel getFondoUser() {
        return fondoUser;
    }

    public void setFondoUser(JLabel fondoUser) {
        this.fondoUser = fondoUser;
    }

    public JComboBox<String> getjComboBox1() {
        return jComboBox1;
    }

    public void setjComboBox1(JComboBox<String> jComboBox1) {
        this.jComboBox1 = jComboBox1;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getJlUser() {
        return jlUser;
    }

    public void setJlUser(JLabel jlUser) {
        this.jlUser = jlUser;
    }

    public JLabel getJlabelDerechos() {
        return jlabelDerechos;
    }

    public void setJlabelDerechos(JLabel jlabelDerechos) {
        this.jlabelDerechos = jlabelDerechos;
    }

    public JLabel getSalir() {
        return salir;
    }

    public void setSalir(JLabel salir) {
        this.salir = salir;
    }

    public JLabel getTitu1() {
        return titu1;
    }

    public void setTitu1(JLabel titu1) {
        this.titu1 = titu1;
    }

    public JLabel getTitu2() {
        return titu2;
    }

    public void setTitu2(JLabel titu2) {
        this.titu2 = titu2;
    }

}
